#!/usr/bin/env bash

# Use neovim for vim if present.
[ -x "$(command -v nvim)" ] && alias vi="nvim " svi="sudo nvim " vim="nvim " svim="sudo nvim " vimdiff="nvim -d "

# Use emacsclient as emacs
[ -x "$(command -v emacsclient)" ] && alias emacsclient="emacsclient -nc" emacs="emacsclient"

# Use $XINITRC variable if file exists.
[ -f "$XINITRC" ] && alias startx="startx $XINITRC"

# Detect which `ls` flavor is in use
if ls --color > /dev/null 2>&1; then # GNU `ls`
	colorflag="--color"
	# export LS_COLORS='no=00:fi=00:di=01;31:ln=01;36:pi=40;33:so=01;35:do=01;35:bd=40;33;01:cd=40;33;01:or=40;31;01:ex=01;32:*.tar=01;31:*.tgz=01;31:*.arj=01;31:*.taz=01;31:*.lzh=01;31:*.zip=01;31:*.z=01;31:*.Z=01;31:*.gz=01;31:*.bz2=01;31:*.deb=01;31:*.rpm=01;31:*.jar=01;31:*.jpg=01;35:*.jpeg=01;35:*.gif=01;35:*.bmp=01;35:*.pbm=01;35:*.pgm=01;35:*.ppm=01;35:*.tga=01;35:*.xbm=01;35:*.xpm=01;35:*.tif=01;35:*.tiff=01;35:*.png=01;35:*.mov=01;35:*.mpg=01;35:*.mpeg=01;35:*.avi=01;35:*.fli=01;35:*.gl=01;35:*.dl=01;35:*.xcf=01;35:*.xwd=01;35:*.ogg=01;35:*.mp3=01;35:*.wav=01;35:'
else # macOS `ls`
	colorflag="-G"
	export LSCOLORS='BxBxhxDxfxhxhxhxhxcxcx'
fi

# Colorize commands when possible.
alias \
	ls="ls -hN ${colorflag} --group-directories-first" \
	grep="grep --color=auto" \
	diff="diff --color=auto" \
	ccat="highlight --out-format=ansi" \
	ip="ip -color=auto"

# Verbosity and settings that you pretty much just always are going to want.
alias \
	cp="cp -ivr" \
	mv="mv -iv" \
	rm="rm -vIrf" \
    ll="ls -hNl ${colorflag} --group-directories-first" \
    la="ls -hNa ${colorflag} --group-directories-first" \
    lla="ls -hNla ${colorflag} --group-directories-first"

# These common commands are just too long! Abbreviate them.
alias \
	ka="killall" \
	g="git" \
	sdn="shutdown -h now" \
	e="$EDITOR" \
	v="$VISUAL" \
	p="pacman" \
	untar="tar -xvf" \
    y="yay" \
	z="zathura" \
    zisu="zinit self-update" \
    ziu="zinit update" \
    ziup="zinit update --parallel" \
    ff="fastfetch" \
	# trem="transmission-remote" \
	# yt="youtube-viewer" \
	# xi="sudo xbps-install" \
	# xr="sudo xbps-remove -R" \
	# xq="xbps-query" \

# Utility commands
alias \
    dots="/usr/bin/git --git-dir=$HOME/.dots/ --work-tree=$HOME"


# sudo not required for some system commands
for command in mount umount sv pacman updatedb su; do
    alias $command="sudo $command"
done; unset command
