#!/bin/sh

# Use neovim for vim if present.
[ -x "$(command -v nvim)" ] && alias vi="nvim " svi="sudo nvim " vim="nvim " svim="sudo nvim " vimdiff="nvim -d "

# Use $XINITRC variable if file exists.
[ -f "$XINITRC" ] && alias startx="startx $XINITRC"

# sudo not required for some system commands
for command in mount umount sv pacman updatedb su shutdown poweroff reboot ; do
	alias $command="sudo $command"
done; unset command

# Verbosity and settings that you pretty much just always are going to want.
alias \
	cp="cp -ivr" \
	mv="mv -iv" \
	rm="rm -vIrf" \
    ll="ls -hNl --color=auto --group-directories-first" \
    la="ls -hNa --color=auto --group-directories-first" \
    lla="ls -hNla --color=auto --group-directories-first"

# Colorize commands when possible.
alias \
	ls="ls -hN --color=auto --group-directories-first" \
	grep="grep --color=auto" \
	diff="diff --color=auto" \
	ccat="highlight --out-format=ansi" \
	ip="ip -color=auto"

# These common commands are just too long! Abbreviate them.
alias \
	ka="killall" \
	g="git" \
	sdn="shutdown -h now" \
	e="$EDITOR" \
	v="$VISUAL" \
	p="pacman" \
    y="yay" \
	z="zathura" \
    zisu="zinit self-update" \
    ziu="zinit update" \
    ziup="zinit update --parallel"
	# trem="transmission-remote" \
	# yt="youtube-viewer" \
	# xi="sudo xbps-install" \
	# xr="sudo xbps-remove -R" \
	# xq="xbps-query" \

# Utility commands
alias \
    config="/usr/bin/git --git-dir=$HOME/.dotfiles/ --work-tree=$HOME"
