#!/bin/sh

if [ -f "${XDG_CONFIG_HOME:-$HOME/.config}/x11/xprofile" ]; then
    . "${XDG_CONFIG_HOME:-$HOME/.config}/x11/xprofile"
else
    . "$HOME/.xprofile"
fi

# Activate DBus variables
dbus-update-activation-environment --all
# exec bspwm
# exec qtile start
# exec awesome
exec i3
