#!/bin/bash

if [ -f "${XDG_CONFIG_HOME:-$HOME/.config}/x11/xprofile" ]; then
    source "${XDG_CONFIG_HOME:-$HOME/.config}/x11/xprofile"
else
    source "$HOME/.xprofile"
fi

# Activate DBus variables
dbus-update-activation-environment --all
exec awesome
