#!/usr/bin/env bash

#CONFIG_FILES="$HOME/.config/waybar/config.jsonc $HOME/.config/waybar/styles.css"
CONFIG_FILES="$HOME/.config/waybar/config.jsonc $HOME/.config/waybar/style.css $HOME/.config/waybar/styles/*.css"

trap "killall waybar" EXIT

while true; do
    waybar &
    inotifywait -e create,modify $CONFIG_FILES
    killall waybar
done
