#!/usr/bin/env bash

case "$1" in
    --sink-raise-volume)
        pulsemixer --id $(pulsemixer --list-sinks | awk '/Default/ { if(match($0, /ID: ([^,]+),/, arr)) print arr[1] }') --change-volume +5 --max-volume 150
        ;;
    --sink-lower-volume)
        pulsemixer --id $(pulsemixer --list-sinks | awk '/Default/ { if(match($0, /ID: ([^,]+),/, arr)) print arr[1] }') --change-volume -5 --max-volume 150
        ;;
    --sink-toggle-mute)
        pulsemixer --id $(pulsemixer --list-sinks | awk '/Default/ { if(match($0, /ID: ([^,]+),/, arr)) print arr[1] }') --toggle-mute
        ;;
    --source-toggle-mute)
        pulsemixer --id $(pulsemixer --list-sources | awk '/Default/ { if(match($0, /ID: ([^,]+),/, arr)) print arr[1] }') --toggle-mute
        ;;
esac
