#!/usr/bin/env bash

# Source `.profile` 'cause we need environment variables
. $HOME/.zprofile

pgrep -x sxhkd > /dev/null || sxhkd &

for monitor in $(bspc query -M); do
	bspc monitor $monitor -d 1 2 3 4
done

bspc config border_width         2
bspc config window_gap           0

bspc config split_ratio          0.50
bspc config single_monocle       true
bspc config gapless_monocle      true
# bspc config borderless_monocle   true

bspc config focused_border_color    "#504945"
bspc config normal_border_color     "#282828"
# bspc config focused_border_color    "#caa6df"
# bspc config normal_border_color     "#1e1e1e"

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Emacs state=tiled
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

[ -f "$HOME/.config/polybar/launch.sh" ] && $HOME/.config/polybar/launch.sh
