#!/usr/bin/env bash

chosen=$(printf "Log Out\nSuspend\nRestart\nPower OFF" | rofi -dmenu -i -theme-str '@import "~/.config/rofi/powermenu.rasi"')

case "$chosen" in
	"Log Out") i3-msg exit ;;
	"Suspend") i3lock -i ~/media/pictures/wallpapers/fractals_gruvbox.jpg && systemctl suspend ;;
	"Restart") systemctl reboot ;;
	"Power OFF") systemctl poweroff ;;
	*) exit 1 ;;
esac
