# Colors (Gruvbox dark)

# Default colors
[colors.primary]
# background = '#32302f'
# background = '#282828'
# background = '#0b0c0c'
# background = '#000000'
background = '#07080c'
foreground = '#ebdbb2'

# Normal colors
# [colors.normal]
# black   = '#282828'
# red     = '#cc241d'
# green   = '#98971a'
# yellow  = '#d79921'
# blue    = '#458588'
# magenta = '#b16286'
# cyan    = '#689d6a'
# white   = '#a89984'
[colors.normal]
black   = '#928374'
red     = '#fb4934'
green   = '#b8bb26'
yellow  = '#fabd2f'
blue    = '#83a598'
magenta = '#d3869b'
cyan    = '#8ec07c'
white   = '#ebdbb2'

# Bright colors
[colors.bright]
black   = '#504945'
red     = '#fb4934'
green   = '#b8bb26'
yellow  = '#fabd2f'
blue    = '#83a598'
magenta = '#d3869b'
cyan    = '#8ec07c'
white   = '#ebdbb2'

[colors]
indexed_colors = [
   { index = 236, color = "0x32302f" },
   { index = 234, color = "0x1d2021" },

   { index = 235, color = "0x282828" },
   { index = 237, color = "0x3c3836" },
   { index = 239, color = "0x504945" },
   { index = 241, color = "0x665c54" },
   { index = 243, color = "0x7c6f64" },

   { index = 244, color = "0x928374" },
   { index = 245, color = "0x928374" },

   { index = 228, color = "0xf2e5bc" },
   { index = 230, color = "0xf9f5d7" },

   { index = 229, color = "0xfbf1c7" },
   { index = 223, color = "0xebdbb2" },
   { index = 250, color = "0xd5c4a1" },
   { index = 248, color = "0xbdae93" },
   { index = 246, color = "0xa89984" },

   { index = 167, color = "0xfb4934" },
   { index = 142, color = "0xb8bb26" },
   { index = 214, color = "0xfabd2f" },
   { index = 109, color = "0x83a598" },
   { index = 175, color = "0xd3869b" },
   { index = 108, color = "0x8ec07c" },
   { index = 208, color = "0xfe8019" },

   { index = 88,  color = "0x9d0006" },
   { index = 100, color = "0x79740e" },
   { index = 136, color = "0xb57614" },
   { index = 24,  color = "0x076678" },
   { index = 96,  color = "0x8f3f71" },
   { index = 66,  color = "0x427b58" },
   { index = 130, color = "0xaf3a03" },
]
