import = [
    "~/.config/alacritty/themes/gruvbox.toml",
    # "~/.config/alacritty/themes/nord.toml",
    # "~/.config/alacritty/themes/modus-vivendi.toml",
    # "~/.config/alacritty/themes/dracula.toml",
    # "~/.config/alacritty/themes/rosepine.toml"
    # "~/.config/alacritty/themes/github.toml"
    # "~/.config/alacritty/themes/tokyonight.toml"
]

[shell]
program = "/bin/zsh"
args = ["--login"]

[window]
# dimensions = { columns = 80, lines = 24 }
padding = { x = 5, y = 5 }
dynamic_padding = true
# opacity = 0.95
opacity = 1

[font]
normal = { family = "monospace", style = "Medium" }
size = 15

[cursor]
style = { shape = "Block", blinking = "Never" }
